### PR TITLE
Remove upper bound version restrictions on all VS SKUs

### LINKED ISSUE #4: Cannot install on latest VS 2019 (16.1)
Should VS 2019 Community be blocked? I'm getting an error installing it on this SKU. Will dig into this more tonight, if it's a problem on my side, but already wanted to start the discussion on it.

image

### PR DESCRIPTION
**Pull request by tiesmaster**
Fixes #4.

### CODE REVIEW

**Comment by tiesmaster** [comment]
I've fixed it by _just_ removing the upper bound on the version restrictions. I looked at a different extension I'm using, how it's done there, and there is no [version restriction there](https://github.com/justcla/HotCommands/blob/3673a1d50a5de90629ad1e0a5af11c9c4a0638e7/HotCommands/source.extension.vsixmanifest#L16), and I doubt that you'd need that on this extension. Let me know, if you look differently at that, and I'm happy to make any changes.

I also noticed that that extension only lists the Community SKU (while I also used that on the Professional SKU), so it might be that it interprets that as the "minimum" SKU supported. I can't test that right now, since I'm on Community atm.

Finally, I didn't remove the restrictions on the targeting pack requirement, though, I doubt that that's actually needed...

**Comment by tiesmaster** [comment]
@jsakamoto Awesome! When do you think you'll have a new version up on the Gallery?

**Comment by jsakamoto** [comment]
Yes, I'm doing now!

**Comment by jsakamoto** [comment]
Done!

image

**Comment by jsakamoto** [comment]
> I also noticed that that extension only lists the Community SKU (while I also used that on the Professional SKU), so it might be that it interprets that as the "minimum" SKU supported. I can't test that right now, since I'm on Community atm.

Thank you for let me know it.

I removed SKU descriptions except Community Edition from my extension package, and uploaded it to Visual Studio Marketplace site.
I could install this extension package into both of VS2019 Community and Enterprise, from Marketplace site.
It looks works fine.

Thanks!

**Comment by tiesmaster** [comment]
Awesome!

**Pull request merged**
