### PR TITLE
Added xtestc, theory

### PR DESCRIPTION
**Pull request by nbarbettini**
Similar syntax to MSTest for classes, plus a snippet for [Theory] tests (xUnit 2.0+)

### CODE REVIEW

**Comment by nbarbettini** [comment]
Your snippets are very useful! I've been using these additional two as well.

**Comment by jsakamoto** [comment]
Thank you for your pull request.
I merged it, and I'm preparing to publish it. Please wait a few minutes or hours.

**Comment by jsakamoto** [comment]
I published it.
https://visualstudiogallery.msdn.microsoft.com/032cd260-d4cd-4849-adff-648ea9a28265

Thank you, @nbarbettini :smile:

**Comment by nbarbettini** [comment]
Cool, glad to contribute!

**Pull request merged**
